### PR TITLE
Small fixes post-launch

### PR DESCRIPTION
**Pull request by MilesHarding**
- Add button to launch slide deck on homepage
- Add Bsky social button to footer
- Reduce size of footer legal links
- Add new field to blog posts to allow offsetting post date without changing URL
- Add missing space on launch blog

### CODE REVIEW

**Review by csyonghe — APPROVED** [review]

**Comment by csyonghe** [comment]
Have you verified this can be built by GitHub pages in your fork?

**Comment by KhronosWebservices** [comment]
> Have you verified this can be built by GitHub pages in your fork?

All changes I verify locally in Jekyll. I have not verified in GitHub.

**Comment by csyonghe** [comment]
On launch date I ran into several issues building the site because there are several uses of Jekyll 4.0 features that GitHub page doesn't recognize. GitHub is still on Jekyll 3.2, and we should make sure not to rely on any features added after that.

**Comment by KhronosWebservices** [comment]
Okay, I will revert to Jenkins 3.2 locally. Nothing added today should be breaking. Only one conditional added which was a copy/paste from an existing conditional, and some text updates.

**Comment by KhronosWebservices** [comment]
Now waiting for GitHub to publish pages on my fork - first time so it might take a few minutes. Once confirmed functional I will post an all-clear over here.

**Review by cheneym2 — APPROVED** [review]

**Comment by KhronosWebservices** [comment]
Build is error free on MilesHarding. Some images were broken due to paths and the test site being in a sub-directory. Can someone squash and merge?

**Pull request merged**
